name: Docker CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  #schedule:
  #  - cron: '0 0 * * 0'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Prepare images
        run: |
            mkdir /tmp/docker.tmp /tmp/docker.tmp.nocc
            cp $GITHUB_WORKSPACE/Dockerfile /tmp/docker.tmp.nocc || exit 1
            cp $GITHUB_WORKSPACE/Dockerfile /tmp/docker.tmp/ || exit 1
            cd /tmp/docker.tmp || exit 1
            sudo apt update
            sudo apt install wget unzip -y
            wget  https://nightly.link/kreatolinux/nyaa3/workflows/build-rootfs/master/builder-rootfs.zip || exit 1
            unzip builder-rootfs.zip
            tar -xvpf kreato-linux-builder-*.tar.gz -C "/tmp/docker.tmp"
            rm -rf builder-rootfs.zip kreato-linux-builder-*.tar.gz
            cd /tmp/docker.tmp.nocc || exit 1
            wget  https://nightly.link/kreatolinux/nyaa3/workflows/build-rootfs/master/nocc-rootfs.zip || exit 1
            unzip nocc-rootfs.zip
            tar -xvpf kreato-linux-nocc-*.tar.gz -C "/tmp/docker.tmp.nocc"
            rm -rf nocc-rootfs.zip kreato-linux-nocc-*.tar.gz
             
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Packages
        run: |
          echo $CR_PAT | docker login ghcr.io -u kreatolinux --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push builder image to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: /tmp/docker.tmp
          push: true
          tags: kreato/builder:latest
      
      - name: Build and push nocc image to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: /tmp/docker.tmp.nocc
          push: true
          tags: kreato/linux:latest
          
      - name: Build and push builder image to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          context: /tmp/docker.tmp
          push: true
          tags: ghcr.io/kreatolinux/builder:latest
      
      - name: Build and push nocc image to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          context: /tmp/docker.tmp.nocc
          push: true
          tags: ghcr.io/kreatolinux/nocc:latest
